### ISSUE TITLE
MANUAL_TRIGGERS warning

### ISSUE THREAD

**Issue by shulcsm** [saxix/django-concurrency#242]
I'm getting 
```DeprecationWarning: MANUAL_TRIGGERS is deprecated and will be removed in 2.5. Use AUTO_CREATE_TRIGGERS```
regardless of the config value. It seems like `MANUAL_TRIGGERS` is still has a default value so it's always set.

**Comment by YAmikep** [comment]
I ran into this today as well.
I was confused because I was not setting `MANUAL_TRIGGERS` anywhere.
I then realized that [it is in the defaults](https://github.com/saxix/django-concurrency/blob/master/src/concurrency/config.py#L24) in the code so it is always set, hence triggering [the warning](https://github.com/saxix/django-concurrency/blob/master/src/concurrency/config.py#L70-L72).

@saxix Any chance a new version can just drop this setting completely?

**Comment by saxix** [comment]
closing because now the default is `AUTO_CREATE_TRIGGERS=true`
