### ISSUE TITLE
Getting RecordModifiedError when trying to load fixtures

### ISSUE THREAD

**Issue by neeket** [saxix/django-concurrency#247]
I am getting **concurrency.exceptions.RecordModifiedError: Problem installing fixture*** Record has been modified** when trying to load fixtures.

Command: python manage.py loaddata someJsonFile.json

**Note:** Full error log and file path omitted

Platform: Windows
Django version: 4.2.2
django-concurrency: 2.4

**Comment by BrentWilkins** [comment]
I just had to work through this myself. The easiest fix for me thus far was to throw:

```python
CONCURRENCY_ENABLED = False
```

into my settings.py. Looking in my DB shows `version: 2` and that's possibly related to the fundamental issue and [this issue](https://github.com/saxix/django-concurrency/issues/150), but not a concern of mine to investigate for now.

That reminds me, did you add the new `version` field to your fixture? I used the find-replace feature in VS Code with regex enabled and these two strings:
* `([^,])\n(        \})`
* `$1,\n            "version": 1\n$2`

As you see I set them all to version 1, so that's why I was surprised to see them all version two, but I think the above linked issue covers that.
